export type TypeNameType = 'normal'
    | 'fire'
    | 'water'
    | 'electric'
    | 'grass'
    | 'ice'
    | 'psychic'
    | 'fighting'
    | 'poison'
    | 'ground'
    | 'flying'
    | 'bug'
    | 'rock'
    | 'ghost'
    | 'dragon';
